version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      RAILS_ENV: development
    networks:
      - test
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails db:migrate && bin/rails db:seed && RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0'"
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - ${POSTGRES_PORT:-5434}:5432
    networks:
      - test
    volumes:
      - pg-data-shop:/var/lib/postgresql/data
      - ./databases/initdb/local:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=shop
volumes:
  pg-data-shop: {}
networks:
  test:
    driver: bridge
